name: Test
on: push
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Say World
        run: echo "Hello"

  test-action:
    if: always()
    name: post workflow
    runs-on: ubuntu-latest
    needs:
      - job-1
      - job-2
    steps:
      - name: slack test
        uses: Asugawara/GithubAction2Slack@main
        with:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          MENTION_MAP: '{"Asugawara": {"FAILURE": "${{secrets.SLACK_USER_ID}}"} , "main": "<!channel>"}'
          STATUS_EMOJI_MAP: '{"SUCCESS": ":circleci-pass:", "FAILURE": ":circleci-fail:"}'
